/*
 *                    BioJava development code
 *
 * This code may be freely distributed and modified under the
 * terms of the GNU Lesser General Public Licence.  This should
 * be distributed with the code.  If you do not have a copy,
 * see:
 *
 *      http://www.gnu.org/copyleft/lesser.html
 *
 * Copyright for this code is held jointly by the individual
 * authors.  These should be listed in @author doc comments.
 *
 * For more information on the BioJava project and its aims,
 * or to join the biojava-l mailing list, visit the home page
 * at:
 *
 *      http://www.biojava.org/
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.17 at 03:04:15 PM PST
//


package org.biojava.nbio.structure.validation;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="atom" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="cid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="clashmag" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="dist" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "clash")
public class Clash {

	@XmlAttribute(name = "atom", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String atom;
	@XmlAttribute(name = "cid", required = true)
	protected BigInteger cid;
	@XmlAttribute(name = "clashmag", required = true)
	protected BigDecimal clashmag;
	@XmlAttribute(name = "dist", required = true)
	protected BigDecimal dist;

	/**
	 * Gets the value of the atom property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getAtom() {
		return atom;
	}

	/**
	 * Sets the value of the atom property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setAtom(String value) {
		this.atom = value;
	}

	/**
	 * Gets the value of the cid property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getCid() {
		return cid;
	}

	/**
	 * Sets the value of the cid property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setCid(BigInteger value) {
		this.cid = value;
	}

	/**
	 * Gets the value of the clashmag property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getClashmag() {
		return clashmag;
	}

	/**
	 * Sets the value of the clashmag property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setClashmag(BigDecimal value) {
		this.clashmag = value;
	}

	/**
	 * Gets the value of the dist property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getDist() {
		return dist;
	}

	/**
	 * Sets the value of the dist property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setDist(BigDecimal value) {
		this.dist = value;
	}

}
