/*
 *                    BioJava development code
 *
 * This code may be freely distributed and modified under the
 * terms of the GNU Lesser General Public Licence.  This should
 * be distributed with the code.  If you do not have a copy,
 * see:
 *
 *      http://www.gnu.org/copyleft/lesser.html
 *
 * Copyright for this code is held jointly by the individual
 * authors.  These should be listed in @author doc comments.
 *
 * For more information on the BioJava project and its aims,
 * or to join the biojava-l mailing list, visit the home page
 * at:
 *
 *      http://www.biojava.org/
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.17 at 03:04:15 PM PST
//


package org.biojava.nbio.structure.validation;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CCP4version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DCC_R" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DCC_Rfree" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="DCC_refinement_program" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="DataAnisotropy" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DataCompleteness" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="EDS_R" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="EDS_resolution" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="EDS_resolution_low" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="Fo_Fc_correlation" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="IoverSigma" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PDB-revision-number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RefmacVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="RestypesNotcheckedForBondAngleGeometry" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TransNCS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TwinFraction" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TwinL" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="TwinL2" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="WilsonBaniso" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="WilsonBestimate" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="XMLcreationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="absolute-percentile-clashscore" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="absolute-percentile-percent-RSRZ-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="absolute-percentile-percent-rama-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="absolute-percentile-percent-rota-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="acentric_outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="attemptedValidationSteps" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="bulk_solvent_b" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="bulk_solvent_k" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="centric_outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="clashscore" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="num-H-reduce" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="num-free-reflections" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="numMillerIndices" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="percent-RSRZ-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="percent-free-reflections" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="percent-rama-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="percent-rota-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="relative-percentile-clashscore" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="relative-percentile-percent-RSRZ-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="relative-percentile-percent-rama-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="relative-percentile-percent-rota-outliers" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="xtriage_input_columns" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Entry")
public class Entry {

	@XmlAttribute(name = "CCP4version", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String ccp4Version;
	@XmlAttribute(name = "DCC_R", required = true)
	protected BigDecimal dccr;
	@XmlAttribute(name = "DCC_Rfree", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String dccRfree;
	@XmlAttribute(name = "DCC_refinement_program", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String dccRefinementProgram;
	@XmlAttribute(name = "DataAnisotropy", required = true)
	protected BigDecimal dataAnisotropy;
	@XmlAttribute(name = "DataCompleteness", required = true)
	protected BigDecimal dataCompleteness;
	@XmlAttribute(name = "EDS_R", required = true)
	protected BigDecimal edsr;
	@XmlAttribute(name = "EDS_resolution", required = true)
	protected BigDecimal edsResolution;
	@XmlAttribute(name = "EDS_resolution_low", required = true)
	protected BigDecimal edsResolutionLow;
	@XmlAttribute(name = "Fo_Fc_correlation", required = true)
	protected BigDecimal foFcCorrelation;
	@XmlAttribute(name = "IoverSigma", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String ioverSigma;
	@XmlAttribute(name = "PDB-revision-number", required = true)
	protected BigInteger pdbRevisionNumber;
	@XmlAttribute(name = "RefmacVersion", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String refmacVersion;
	@XmlAttribute(name = "RestypesNotcheckedForBondAngleGeometry", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String restypesNotcheckedForBondAngleGeometry;
	@XmlAttribute(name = "TransNCS", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String transNCS;
	@XmlAttribute(name = "TwinFraction", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String twinFraction;
	@XmlAttribute(name = "TwinL", required = true)
	protected BigDecimal twinL;
	@XmlAttribute(name = "TwinL2", required = true)
	protected BigDecimal twinL2;
	@XmlAttribute(name = "WilsonBaniso", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String wilsonBaniso;
	@XmlAttribute(name = "WilsonBestimate", required = true)
	protected BigDecimal wilsonBestimate;
	@XmlAttribute(name = "XMLcreationDate", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String xmLcreationDate;
	@XmlAttribute(name = "absolute-percentile-clashscore", required = true)
	protected BigDecimal absolutePercentileClashscore;
	@XmlAttribute(name = "absolute-percentile-percent-RSRZ-outliers", required = true)
	protected BigDecimal absolutePercentilePercentRSRZOutliers;
	@XmlAttribute(name = "absolute-percentile-percent-rama-outliers", required = true)
	protected BigDecimal absolutePercentilePercentRamaOutliers;
	@XmlAttribute(name = "absolute-percentile-percent-rota-outliers", required = true)
	protected BigDecimal absolutePercentilePercentRotaOutliers;

	@XmlAttribute(name = "absolute-percentile-DCC_Rfree", required = false)
	protected BigDecimal absolutePercentileDCCRfree;
	@XmlAttribute(name = "relative-percentile-DCC_Rfree", required = false)
	protected BigDecimal relativePercentileDCCRfree;


	@XmlAttribute(name = "RNAsuiteness", required = false)
	protected BigDecimal rnaSuiteness;

	@XmlAttribute(name = "absolute-percentile-RNAsuiteness", required = false)
	protected BigDecimal absolutePercentialRNAsuiteness;

	@XmlAttribute(name = "relative-percentile-RNAsuiteness", required = false)
	protected BigDecimal relativePercentileRNAsuiteness;


	@XmlAttribute(name = "acentric_outliers", required = true)
	protected BigInteger acentricOutliers;
	@XmlAttribute(name = "attemptedValidationSteps", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String attemptedValidationSteps;
	@XmlAttribute(name = "bulk_solvent_b", required = true)
	protected BigDecimal bulkSolventB;
	@XmlAttribute(name = "bulk_solvent_k", required = true)
	protected BigDecimal bulkSolventK;
	@XmlAttribute(name = "centric_outliers", required = true)
	protected BigInteger centricOutliers;
	@XmlAttribute(name = "clashscore", required = true)
	protected BigDecimal clashscore;
	@XmlAttribute(name = "num-H-reduce", required = true)
	protected BigInteger numHReduce;
	@XmlAttribute(name = "num-free-reflections", required = true)
	protected BigInteger numFreeReflections;
	@XmlAttribute(name = "numMillerIndices", required = true)
	protected BigInteger numMillerIndices;
	@XmlAttribute(name = "percent-RSRZ-outliers", required = true)
	protected BigDecimal percentRSRZOutliers;
	@XmlAttribute(name = "percent-free-reflections", required = true)
	protected BigDecimal percentFreeReflections;
	@XmlAttribute(name = "percent-rama-outliers", required = true)
	protected BigDecimal percentRamaOutliers;
	@XmlAttribute(name = "percent-rota-outliers", required = true)
	protected BigDecimal percentRotaOutliers;
	@XmlAttribute(name = "relative-percentile-clashscore", required = true)
	protected BigDecimal relativePercentileClashscore;
	@XmlAttribute(name = "relative-percentile-percent-RSRZ-outliers", required = true)
	protected BigDecimal relativePercentilePercentRSRZOutliers;
	@XmlAttribute(name = "relative-percentile-percent-rama-outliers", required = true)
	protected BigDecimal relativePercentilePercentRamaOutliers;
	@XmlAttribute(name = "relative-percentile-percent-rota-outliers", required = true)
	protected BigDecimal relativePercentilePercentRotaOutliers;
	@XmlAttribute(name = "xtriage_input_columns", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String xtriageInputColumns;

	/**
	 * Gets the value of the ccp4Version property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getCCP4Version() {
		return ccp4Version;
	}

	/**
	 * Sets the value of the ccp4Version property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setCCP4Version(String value) {
		this.ccp4Version = value;
	}

	/**
	 * Gets the value of the dccr property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getDCCR() {
		return dccr;
	}

	/**
	 * Sets the value of the dccr property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setDCCR(BigDecimal value) {
		this.dccr = value;
	}

	/**
	 * Gets the value of the dccRfree property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getDCCRfree() {
		return dccRfree;
	}

	/**
	 * Sets the value of the dccRfree property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setDCCRfree(String value) {
		this.dccRfree = value;
	}

	/**
	 * Gets the value of the dccRefinementProgram property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getDCCRefinementProgram() {
		return dccRefinementProgram;
	}

	/**
	 * Sets the value of the dccRefinementProgram property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setDCCRefinementProgram(String value) {
		this.dccRefinementProgram = value;
	}

	/**
	 * Gets the value of the dataAnisotropy property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getDataAnisotropy() {
		return dataAnisotropy;
	}

	/**
	 * Sets the value of the dataAnisotropy property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setDataAnisotropy(BigDecimal value) {
		this.dataAnisotropy = value;
	}

	/**
	 * Gets the value of the dataCompleteness property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getDataCompleteness() {
		return dataCompleteness;
	}

	/**
	 * Sets the value of the dataCompleteness property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setDataCompleteness(BigDecimal value) {
		this.dataCompleteness = value;
	}

	/**
	 * Gets the value of the edsr property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEDSR() {
		return edsr;
	}

	/**
	 * Sets the value of the edsr property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEDSR(BigDecimal value) {
		this.edsr = value;
	}

	/**
	 * Gets the value of the edsResolution property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEDSResolution() {
		return edsResolution;
	}

	/**
	 * Sets the value of the edsResolution property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEDSResolution(BigDecimal value) {
		this.edsResolution = value;
	}

	/**
	 * Gets the value of the edsResolutionLow property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getEDSResolutionLow() {
		return edsResolutionLow;
	}

	/**
	 * Sets the value of the edsResolutionLow property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setEDSResolutionLow(BigDecimal value) {
		this.edsResolutionLow = value;
	}

	/**
	 * Gets the value of the foFcCorrelation property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getFoFcCorrelation() {
		return foFcCorrelation;
	}

	/**
	 * Sets the value of the foFcCorrelation property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setFoFcCorrelation(BigDecimal value) {
		this.foFcCorrelation = value;
	}

	/**
	 * Gets the value of the ioverSigma property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getIoverSigma() {
		return ioverSigma;
	}

	/**
	 * Sets the value of the ioverSigma property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setIoverSigma(String value) {
		this.ioverSigma = value;
	}

	/**
	 * Gets the value of the pdbRevisionNumber property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getPDBRevisionNumber() {
		return pdbRevisionNumber;
	}

	/**
	 * Sets the value of the pdbRevisionNumber property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setPDBRevisionNumber(BigInteger value) {
		this.pdbRevisionNumber = value;
	}

	/**
	 * Gets the value of the refmacVersion property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getRefmacVersion() {
		return refmacVersion;
	}

	/**
	 * Sets the value of the refmacVersion property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setRefmacVersion(String value) {
		this.refmacVersion = value;
	}

	/**
	 * Gets the value of the restypesNotcheckedForBondAngleGeometry property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getRestypesNotcheckedForBondAngleGeometry() {
		return restypesNotcheckedForBondAngleGeometry;
	}

	/**
	 * Sets the value of the restypesNotcheckedForBondAngleGeometry property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setRestypesNotcheckedForBondAngleGeometry(String value) {
		this.restypesNotcheckedForBondAngleGeometry = value;
	}

	/**
	 * Gets the value of the transNCS property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getTransNCS() {
		return transNCS;
	}

	/**
	 * Sets the value of the transNCS property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setTransNCS(String value) {
		this.transNCS = value;
	}

	/**
	 * Gets the value of the twinFraction property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getTwinFraction() {
		return twinFraction;
	}

	/**
	 * Sets the value of the twinFraction property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setTwinFraction(String value) {
		this.twinFraction = value;
	}

	/**
	 * Gets the value of the twinL property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getTwinL() {
		return twinL;
	}

	/**
	 * Sets the value of the twinL property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setTwinL(BigDecimal value) {
		this.twinL = value;
	}

	/**
	 * Gets the value of the twinL2 property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getTwinL2() {
		return twinL2;
	}

	/**
	 * Sets the value of the twinL2 property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setTwinL2(BigDecimal value) {
		this.twinL2 = value;
	}

	/**
	 * Gets the value of the wilsonBaniso property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getWilsonBaniso() {
		return wilsonBaniso;
	}

	/**
	 * Sets the value of the wilsonBaniso property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setWilsonBaniso(String value) {
		this.wilsonBaniso = value;
	}

	/**
	 * Gets the value of the wilsonBestimate property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getWilsonBestimate() {
		return wilsonBestimate;
	}

	/**
	 * Sets the value of the wilsonBestimate property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setWilsonBestimate(BigDecimal value) {
		this.wilsonBestimate = value;
	}

	/**
	 * Gets the value of the xmLcreationDate property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getXMLcreationDate() {
		return xmLcreationDate;
	}

	/**
	 * Sets the value of the xmLcreationDate property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setXMLcreationDate(String value) {
		this.xmLcreationDate = value;
	}

	/**
	 * Gets the value of the absolutePercentileClashscore property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAbsolutePercentileClashscore() {
		return absolutePercentileClashscore;
	}

	/**
	 * Sets the value of the absolutePercentileClashscore property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAbsolutePercentileClashscore(BigDecimal value) {
		this.absolutePercentileClashscore = value;
	}

	/**
	 * Gets the value of the absolutePercentilePercentRSRZOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAbsolutePercentilePercentRSRZOutliers() {
		return absolutePercentilePercentRSRZOutliers;
	}

	/**
	 * Sets the value of the absolutePercentilePercentRSRZOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAbsolutePercentilePercentRSRZOutliers(BigDecimal value) {
		this.absolutePercentilePercentRSRZOutliers = value;
	}

	/**
	 * Gets the value of the absolutePercentilePercentRamaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAbsolutePercentilePercentRamaOutliers() {
		return absolutePercentilePercentRamaOutliers;
	}

	/**
	 * Sets the value of the absolutePercentilePercentRamaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAbsolutePercentilePercentRamaOutliers(BigDecimal value) {
		this.absolutePercentilePercentRamaOutliers = value;
	}

	/**
	 * Gets the value of the absolutePercentilePercentRotaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getAbsolutePercentilePercentRotaOutliers() {
		return absolutePercentilePercentRotaOutliers;
	}

	/**
	 * Sets the value of the absolutePercentilePercentRotaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setAbsolutePercentilePercentRotaOutliers(BigDecimal value) {
		this.absolutePercentilePercentRotaOutliers = value;
	}

	public BigDecimal getAbsolutePercentileDCCRfree() {
		return absolutePercentileDCCRfree;
	}

	public void setAbsolutePercentileDCCRfree(
			BigDecimal absolutePercentileDCCRfree) {
		this.absolutePercentileDCCRfree = absolutePercentileDCCRfree;
	}

	public BigDecimal getRelativePercentileDCCRfree() {
		return relativePercentileDCCRfree;
	}

	public void setRelativePercentileDCCRfree(
			BigDecimal relativePercentileDCCRfree) {
		this.relativePercentileDCCRfree = absolutePercentileDCCRfree;
	}

	/**
	 * Gets the value of the acentricOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getAcentricOutliers() {
		return acentricOutliers;
	}

	/**
	 * Sets the value of the acentricOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setAcentricOutliers(BigInteger value) {
		this.acentricOutliers = value;
	}

	/**
	 * Gets the value of the attemptedValidationSteps property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getAttemptedValidationSteps() {
		return attemptedValidationSteps;
	}

	/**
	 * Sets the value of the attemptedValidationSteps property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setAttemptedValidationSteps(String value) {
		this.attemptedValidationSteps = value;
	}

	/**
	 * Gets the value of the bulkSolventB property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getBulkSolventB() {
		return bulkSolventB;
	}

	/**
	 * Sets the value of the bulkSolventB property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setBulkSolventB(BigDecimal value) {
		this.bulkSolventB = value;
	}

	/**
	 * Gets the value of the bulkSolventK property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getBulkSolventK() {
		return bulkSolventK;
	}

	/**
	 * Sets the value of the bulkSolventK property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setBulkSolventK(BigDecimal value) {
		this.bulkSolventK = value;
	}

	/**
	 * Gets the value of the centricOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getCentricOutliers() {
		return centricOutliers;
	}

	/**
	 * Sets the value of the centricOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setCentricOutliers(BigInteger value) {
		this.centricOutliers = value;
	}

	/**
	 * Gets the value of the clashscore property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getClashscore() {
		return clashscore;
	}

	/**
	 * Sets the value of the clashscore property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setClashscore(BigDecimal value) {
		this.clashscore = value;
	}

	/**
	 * Gets the value of the numHReduce property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getNumHReduce() {
		return numHReduce;
	}

	/**
	 * Sets the value of the numHReduce property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setNumHReduce(BigInteger value) {
		this.numHReduce = value;
	}

	/**
	 * Gets the value of the numFreeReflections property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getNumFreeReflections() {
		return numFreeReflections;
	}

	/**
	 * Sets the value of the numFreeReflections property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setNumFreeReflections(BigInteger value) {
		this.numFreeReflections = value;
	}

	/**
	 * Gets the value of the numMillerIndices property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *
	 */
	public BigInteger getNumMillerIndices() {
		return numMillerIndices;
	}

	/**
	 * Sets the value of the numMillerIndices property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *
	 */
	public void setNumMillerIndices(BigInteger value) {
		this.numMillerIndices = value;
	}

	/**
	 * Gets the value of the percentRSRZOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getPercentRSRZOutliers() {
		return percentRSRZOutliers;
	}

	/**
	 * Sets the value of the percentRSRZOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setPercentRSRZOutliers(BigDecimal value) {
		this.percentRSRZOutliers = value;
	}

	/**
	 * Gets the value of the percentFreeReflections property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getPercentFreeReflections() {
		return percentFreeReflections;
	}

	/**
	 * Sets the value of the percentFreeReflections property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setPercentFreeReflections(BigDecimal value) {
		this.percentFreeReflections = value;
	}

	/**
	 * Gets the value of the percentRamaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getPercentRamaOutliers() {
		return percentRamaOutliers;
	}

	/**
	 * Sets the value of the percentRamaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setPercentRamaOutliers(BigDecimal value) {
		this.percentRamaOutliers = value;
	}

	/**
	 * Gets the value of the percentRotaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getPercentRotaOutliers() {
		return percentRotaOutliers;
	}

	/**
	 * Sets the value of the percentRotaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setPercentRotaOutliers(BigDecimal value) {
		this.percentRotaOutliers = value;
	}

	/**
	 * Gets the value of the relativePercentileClashscore property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getRelativePercentileClashscore() {
		return relativePercentileClashscore;
	}

	/**
	 * Sets the value of the relativePercentileClashscore property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setRelativePercentileClashscore(BigDecimal value) {
		this.relativePercentileClashscore = value;
	}

	/**
	 * Gets the value of the relativePercentilePercentRSRZOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getRelativePercentilePercentRSRZOutliers() {
		return relativePercentilePercentRSRZOutliers;
	}

	/**
	 * Sets the value of the relativePercentilePercentRSRZOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setRelativePercentilePercentRSRZOutliers(BigDecimal value) {
		this.relativePercentilePercentRSRZOutliers = value;
	}

	/**
	 * Gets the value of the relativePercentilePercentRamaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getRelativePercentilePercentRamaOutliers() {
		return relativePercentilePercentRamaOutliers;
	}

	/**
	 * Sets the value of the relativePercentilePercentRamaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setRelativePercentilePercentRamaOutliers(BigDecimal value) {
		this.relativePercentilePercentRamaOutliers = value;
	}

	/**
	 * Gets the value of the relativePercentilePercentRotaOutliers property.
	 *
	 * @return
	 *     possible object is
	 *     {@link BigDecimal }
	 *
	 */
	public BigDecimal getRelativePercentilePercentRotaOutliers() {
		return relativePercentilePercentRotaOutliers;
	}

	/**
	 * Sets the value of the relativePercentilePercentRotaOutliers property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link BigDecimal }
	 *
	 */
	public void setRelativePercentilePercentRotaOutliers(BigDecimal value) {
		this.relativePercentilePercentRotaOutliers = value;
	}

	/**
	 * Gets the value of the xtriageInputColumns property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getXtriageInputColumns() {
		return xtriageInputColumns;
	}

	/**
	 * Sets the value of the xtriageInputColumns property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setXtriageInputColumns(String value) {
		this.xtriageInputColumns = value;
	}

	public BigDecimal getRnaSuiteness() {
		return rnaSuiteness;
	}

	public void setRnaSuiteness(BigDecimal rnaSuiteness) {
		this.rnaSuiteness = rnaSuiteness;
	}

	public BigDecimal getAbsolutePercentialRNAsuiteness() {
		return absolutePercentialRNAsuiteness;
	}

	public void setAbsolutePercentialRNAsuiteness(
			BigDecimal absolutePercentialRNAsuiteness) {
		this.absolutePercentialRNAsuiteness = absolutePercentialRNAsuiteness;
	}

	public BigDecimal getRelativePercentileRNAsuiteness() {
		return relativePercentileRNAsuiteness;
	}

	public void setRelativePercentileRNAsuiteness(
			BigDecimal relativePercentileRNAsuiteness) {
		this.relativePercentileRNAsuiteness = relativePercentileRNAsuiteness;
	}



}
