/*
 *                    BioJava development code
 *
 * This code may be freely distributed and modified under the
 * terms of the GNU Lesser General Public Licence.  This should
 * be distributed with the code.  If you do not have a copy,
 * see:
 *
 *      http://www.gnu.org/copyleft/lesser.html
 *
 * Copyright for this code is held jointly by the individual
 * authors.  These should be listed in @author doc comments.
 *
 * For more information on the BioJava project and its aims,
 * or to join the biojava-l mailing list, visit the home page
 * at:
 *
 *      http://www.biojava.org/
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.17 at 03:04:15 PM PST
//


package org.biojava.nbio.structure.validation;

import javax.xml.bind.annotation.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Entry"/>
 *         &lt;element ref="{}ModelledSubgroup" maxOccurs="unbounded"/>
 *         &lt;element ref="{}programs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"entry",
	"modelledSubgroup",
	"programs"
})
@XmlRootElement(name = "wwPDB-validation-information")
public class WwPDBValidationInformation implements Serializable {

	private static final long serialVersionUID = -996804963717482650L;

	@XmlElement(name = "Entry", required = true)
	protected Entry entry;
	@XmlElement(name = "ModelledSubgroup", required = true)
	protected List<ModelledSubgroup> modelledSubgroup;
	@XmlElement(required = true)
	protected Programs programs;

	/**
	 * Gets the value of the entry property.
	 *
	 * @return
	 *     possible object is
	 *     {@link Entry }
	 *
	 */
	public Entry getEntry() {
		return entry;
	}

	/**
	 * Sets the value of the entry property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link Entry }
	 *
	 */
	public void setEntry(Entry value) {
		this.entry = value;
	}

	/**
	 * Gets the value of the modelledSubgroup property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the modelledSubgroup property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getModelledSubgroup().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ModelledSubgroup }
	 *
	 *
	 */
	public List<ModelledSubgroup> getModelledSubgroup() {
		if (modelledSubgroup == null) {
			modelledSubgroup = new ArrayList<ModelledSubgroup>();
		}
		return this.modelledSubgroup;
	}

	/**
	 * Gets the value of the programs property.
	 *
	 * @return
	 *     possible object is
	 *     {@link Programs }
	 *
	 */
	public Programs getPrograms() {
		return programs;
	}

	/**
	 * Sets the value of the programs property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link Programs }
	 *
	 */
	public void setPrograms(Programs value) {
		this.programs = value;
	}

}
