//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.09 at 10:02:06 AM SGT 
//


package org.biojava3.aaproperties.molecularweight.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}molecular_formula"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="E"/>
 *             &lt;enumeration value="F"/>
 *             &lt;enumeration value="G"/>
 *             &lt;enumeration value="H"/>
 *             &lt;enumeration value="I"/>
 *             &lt;enumeration value="K"/>
 *             &lt;enumeration value="L"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="R"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="V"/>
 *             &lt;enumeration value="W"/>
 *             &lt;enumeration value="Y"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="short" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Ala"/>
 *             &lt;enumeration value="Arg"/>
 *             &lt;enumeration value="Asn"/>
 *             &lt;enumeration value="Asp"/>
 *             &lt;enumeration value="Cys"/>
 *             &lt;enumeration value="Gln"/>
 *             &lt;enumeration value="Glu"/>
 *             &lt;enumeration value="Gly"/>
 *             &lt;enumeration value="His"/>
 *             &lt;enumeration value="Ile"/>
 *             &lt;enumeration value="Leu"/>
 *             &lt;enumeration value="Lys"/>
 *             &lt;enumeration value="Met"/>
 *             &lt;enumeration value="Phe"/>
 *             &lt;enumeration value="Pro"/>
 *             &lt;enumeration value="Ser"/>
 *             &lt;enumeration value="Thr"/>
 *             &lt;enumeration value="Trp"/>
 *             &lt;enumeration value="Tyr"/>
 *             &lt;enumeration value="Val"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Alanine"/>
 *             &lt;enumeration value="Arginine"/>
 *             &lt;enumeration value="Asparagine"/>
 *             &lt;enumeration value="Aspartic Acid"/>
 *             &lt;enumeration value="Cysteine"/>
 *             &lt;enumeration value="Glutamic Acid"/>
 *             &lt;enumeration value="Glutamine"/>
 *             &lt;enumeration value="Glycine"/>
 *             &lt;enumeration value="Histidine"/>
 *             &lt;enumeration value="Isoleucine"/>
 *             &lt;enumeration value="Leucine"/>
 *             &lt;enumeration value="Lysine"/>
 *             &lt;enumeration value="Methionine"/>
 *             &lt;enumeration value="Phenylalanine"/>
 *             &lt;enumeration value="Proline"/>
 *             &lt;enumeration value="Serine"/>
 *             &lt;enumeration value="Threonine"/>
 *             &lt;enumeration value="Tryptophan"/>
 *             &lt;enumeration value="Tyrosine"/>
 *             &lt;enumeration value="Valine"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "molecularFormula"
})
@XmlRootElement(name = "amino_acid")
public class AminoAcid {

    @XmlElement(name = "molecular_formula", required = true)
    protected MolecularFormula molecularFormula;
    @XmlAttribute(name = "symbol", required = true)
    protected String symbol;
    @XmlAttribute(name = "short", required = true)
    protected String _short;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the molecularFormula property.
     * 
     * @return
     *     possible object is
     *     {@link MolecularFormula }
     *     
     */
    public MolecularFormula getMolecularFormula() {
        return molecularFormula;
    }

    /**
     * Sets the value of the molecularFormula property.
     * 
     * @param value
     *     allowed object is
     *     {@link MolecularFormula }
     *     
     */
    public void setMolecularFormula(MolecularFormula value) {
        this.molecularFormula = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the short property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShort() {
        return _short;
    }

    /**
     * Sets the value of the short property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShort(String value) {
        this._short = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
