//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.09 at 10:02:06 AM SGT 
//


package org.biojava3.aaproperties.molecularweight.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the molecularweight.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: molecularweight.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Element }
     * @return an instance of Element
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Compounds }
     * @return an instance of Compounds
     */
    public Compounds createCompounds() {
        return new Compounds();
    }

    /**
     * Create an instance of {@link Elements }
     * @return an instance of Elements
     * 
     */
    public Elements createElements() {
        return new Elements();
    }

    /**
     * Create an instance of {@link AminoAcids }
     * @return an instance of AminoAcids
     */
    public AminoAcids createAminoAcids() {
        return new AminoAcids();
    }

    /**
     * Create an instance of {@link AminoAcid }
     * @return an instance of AminoAcid
     */
    public AminoAcid createAminoAcid() {
        return new AminoAcid();
    }

    /**
     * Create an instance of {@link MolecularFormula }
     * @return an instance of MolecularFormula
     */
    public MolecularFormula createMolecularFormula() {
        return new MolecularFormula();
    }

}
